### ISSUE TITLE
Read `required_keys` from config file

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#978]
As part of the move towards more flexible metadata handling we should be able to read the keys we use to create unique Datasources from a configuration file.

1. Store the default required_keys in a TOML file that's created in the config folder in the object store root
2. Allow users to create a new file with the updated keys
3. When we check the required keys we'll read either the default or the other file in the folder, raising an error if there's more than 2 files

We could have a simple folder structure in the object store root directory

```
config/
    db/                             <- can contain database specific config files / keys etc
    identifying_keys/      <- contain the files we use to create unique Datasources
    version.json              <- version of OpenGHG this config setup was created with
```

I don't think we should have a command line interface to set this up as it then makes it too easy for the file to be modified accidentally.

### Round 2

A slightly cleaner option

```
config/
    db/                             <- can contain database specific config files / keys etc
        config.toml            <- database config file, currently empty
        metadata_keys.toml     <- read the required keys from here
    version.json              <- version of OpenGHG this config setup was created with
```

Folder structure created by OpenGHG on first run. The keys config file will then be read on standardisation.

**Comment by brendan-m-murphy** [comment]
Are you thinking that the user specified version created/modified will be by some function in openghg?

I'm not sure we need two files. Presumably there will be a default version in openghg that is copied to each object store, so the defaults could be recovered.

**Comment by gareth-j** [comment]
At the moment we have these defaults

```toml
[default_metakeys]
boundary_conditions = [ "species", "bc_input", "domain",]

eulerian_model = [ "model", "species", "date",]

flux = [ "species", "source", "domain", "database", "database_version", "model",]

footprints = [ "site", "model", "inlet", "domain", "high_time_resolution", 
                "high_spatial_resolution", "short_lifetime", "species", "met_model",]

obscolumn = [ "satellite", "selection", "domain", "site", "species", "network",]

obssurface = [ "species", "site", "sampling_period", "station_long_name", "inlet", 
                "instrument", "network", "source_format", "data_source", "icos_data_level", "data_type",]

```
